### ISSUE TITLE
Problem at compiling

### ISSUE THREAD

**Issue by bitfreaks** [greggman/unity-webgl-copy-and-paste#4]
Hi Greg,

Thanks for the script, but when I import it and build my project - I am getting the below error in the console:

`wasm streaming compile failed: LinkError: import object field '_initWebGLCopyAndPaste' is not a Function`

Any idea how to fix it?

**Comment by greggman** [comment]
what version of unity?

**Comment by bitfreaks** [comment]
Hey Greg, thanks for replying.

Unity 2020.3.19f1

**Comment by greggman** [comment]
try this one

https://github.com/greggman/unity-webgl-copy-and-paste/releases/latest

**Comment by bitfreaks** [comment]
Cool! Will try it out tomorrow and let you know. Appreciate your time!

**Comment by bitfreaks** [comment]
Works like a charm! Thanks Greg!!
